### PR TITLE
Fix QUnit nested suites

### LINKED ISSUE #57: Fix QUnit Adapter
After the [new testing](https://github.com/js-reporters/js-reporters/tree/9aba15bc8a801b5a1b8f0829b7fb534cfa46317a/test/integration) we need to fix some issues in the adapter.

## Issues

[1] The `QUnit global module` is emitted also on [suiteStart](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L46) event, as also on [suiteEnd](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L78).

[2] Passing tests are failing, because QUnit is checking for an `assertion` and in our [test fixture](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/test/fixtures/qunit.js) there are none.

[3] Objects are **emitted** are then **mutated**. [Emitted](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L51) and [mutated](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L63-L72).

[4] The current adapter do not permit `suites` with the [same name](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L29).

[5] Skipped tests have as `runtime 0ms`.

[6] Nested modules run. QUnit runs the nested modules (suites) from the inner most suite to the outter most suite.

[7] QUnit provide already for nested modules a concatenated name. The suite names are separated by the character ">", ex: `outter suite > inner suite`.

[8] Also for failing tests, QUnit is taking the error and creates an object with some more properties, so the deep equal assertion will fail.

[9] The `globalSuite` emitted on `suiteStart` is not created properly.

## Solutions

- [x] [1] - Check on the `suiteStart` and `suiteEnd` event, that the received module is not the `globalModule` and only then emit a converted suite.

- [x] [2] We can add a dummyAssertion in our fixture, like: `ok(true)`.

- [x] [3], [4] - We should convert the `modules` and `tests` every time we are emitting something, the same as in the [MochaAdapter](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/MochaAdapter.js)

- [x] [5] I think it would be a good thing for QUnit to also put the `runtime` of a  `skipped test` to be `undefined`, because that test is no running, so it doesn't make sens to have a runtime. For now we can set it to undefined [by hand](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L71) in our adapter.

- [x] [6] We will run it like Mocha, from the outer most to the inner most, also because the QUnit reporter displays tests this way.

- [x] [7] Remove the ">" character.

- [x] [8] We can do something like with the [runtimes](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/test/integration/adapters.js#L52-L58), to make a function that checks that the errors are conform with the QUnit errors and then override them.

- [x] [9] Create a function that builds the global suite for the runStart and runEnd events.

### PR DESCRIPTION
**Pull request by flore77**
Fixes #57, [6] nested modules.

### CODE REVIEW

**Comment by flore77** [comment]
@jzaefferer please take a look :smiley: 

We must do something with the tests runtime range test, `f2b23c8` failed for that reason.

**Comment by jzaefferer** [comment]
Sucks that we can only emit at the end of the run, but that's certainly a good reason to get the reporter implemented natively in QUnit itself asap.

File: lib/adapters/QUnitAdapter.js [hunk 1]
```diff
@@ -6,67 +6,37 @@ export default class QUnitAdapter extends EventEmitter {
...
-    QUnit.moduleStart(this.onModuleStart.bind(this))
     QUnit.testStart(this.onTestStart.bind(this))
     QUnit.log(this.onLog.bind(this))
     QUnit.testDone(this.onTestDone.bind(this))
-    QUnit.moduleDone(this.onModuleDone.bind(this))
     QUnit.done(this.onDone.bind(this))
 
     this.testsDetails = {}
-    this.emitGlobal = false
+    this.type = {
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: I don't like this object, same issue as the event name abstraction we discussed a while ago. Passing `'start'` and `'end'`as strings will do the trick.

Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Let's try to get rid of the `type` argument entirely, and use separate `create` methods instead. `createTestStart` and `createTestEnd` should be obvious enough to implement. As for the other two, something like this, simplified using `map` instead of `let of / push`:

```js
createSuiteStart () {
  return new Suite(suite.name,
    suite.childSuites.map(this.createSuiteStart),
    suite.tests.map(this.createTestStart))
}

createSuiteEnd () {
  return new Suite(suite.name,
    suite.childSuites.map(this.createSuiteEnd),
    suite.tests.map(this.createTestEnd))
}
```
May need to explicitly bind both functions inside the constructor, to be able to pass them to `map` and still get the same `this` reference.

File: lib/adapters/QUnitAdapter.js [hunk 2]
```diff
@@ -82,40 +52,39 @@ export default class QUnitAdapter extends EventEmitter {
...
+      modules = this.QUnit.config.modules
     }
 
     // Build a list with all suites.
-    for (let module of this.QUnit.config.modules) {
-      if (!this.isGlobalModule(module)) {
-        suites.push(this.convertModule(module))
-      }
+    for (let module of modules) {
+      suites.push(this.convertModule(module))
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Should also use `map` here.

**Comment by flore77** [comment]
Done.

File: lib/adapters/QUnitAdapter.js [hunk 3]
```diff
@@ -82,41 +48,38 @@ export default class QUnitAdapter extends EventEmitter {
...
+      modules = this.QUnit.config.modules
     }
 
     // Build a list with all suites.
-    for (let module of this.QUnit.config.modules) {
-      if (!this.isGlobalModule(module)) {
-        suites.push(this.convertModule(module))
-      }
-    }
+    suites = modules.map(this.convertModule)
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Now that we don't need the initializer, let's remove the declaration above, and use `let suites =...` instead. Check if that can be applied for other vars as well.

File: lib/adapters/QUnitAdapter.js [hunk 4]
```diff
@@ -157,24 +120,55 @@ export default class QUnitAdapter extends EventEmitter {
...
+
+  createTestStart (test) {
+    return new Test(test.testName, test.suiteName)
   }
 
-  onModuleStart (details) {
-    if (!this.isGlobalModule(details)) {
-      this.emit('suiteStart', this.convertModule(details))
+  createTestEnd (test) {
+    var testDetails = this.testsDetails[test.testId]
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Give this a try:
```
const { status, runtime, errors } = this.testsDetails[test.testId]
return new Test(test.testName, test.suiteName, status, runtime, errors)
```

**Comment by flore77** [comment]
Can this be landed?

**Comment by jzaefferer** [comment]
👍
