### PR TITLE
Fix qunit adapter

### LINKED ISSUE #57: Fix QUnit Adapter
After the [new testing](https://github.com/js-reporters/js-reporters/tree/9aba15bc8a801b5a1b8f0829b7fb534cfa46317a/test/integration) we need to fix some issues in the adapter.

## Issues

[1] The `QUnit global module` is emitted also on [suiteStart](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L46) event, as also on [suiteEnd](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L78).

[2] Passing tests are failing, because QUnit is checking for an `assertion` and in our [test fixture](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/test/fixtures/qunit.js) there are none.

[3] Objects are **emitted** are then **mutated**. [Emitted](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L51) and [mutated](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L63-L72).

[4] The current adapter do not permit `suites` with the [same name](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L29).

[5] Skipped tests have as `runtime 0ms`.

[6] Nested modules run. QUnit runs the nested modules (suites) from the inner most suite to the outter most suite.

[7] QUnit provide already for nested modules a concatenated name. The suite names are separated by the character ">", ex: `outter suite > inner suite`.

[8] Also for failing tests, QUnit is taking the error and creates an object with some more properties, so the deep equal assertion will fail.

[9] The `globalSuite` emitted on `suiteStart` is not created properly.

## Solutions

- [x] [1] - Check on the `suiteStart` and `suiteEnd` event, that the received module is not the `globalModule` and only then emit a converted suite.

- [x] [2] We can add a dummyAssertion in our fixture, like: `ok(true)`.

- [x] [3], [4] - We should convert the `modules` and `tests` every time we are emitting something, the same as in the [MochaAdapter](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/MochaAdapter.js)

- [x] [5] I think it would be a good thing for QUnit to also put the `runtime` of a  `skipped test` to be `undefined`, because that test is no running, so it doesn't make sens to have a runtime. For now we can set it to undefined [by hand](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/lib/adapters/QUnitAdapter.js#L71) in our adapter.

- [x] [6] We will run it like Mocha, from the outer most to the inner most, also because the QUnit reporter displays tests this way.

- [x] [7] Remove the ">" character.

- [x] [8] We can do something like with the [runtimes](https://github.com/js-reporters/js-reporters/blob/49b51f43ce8ed2d1b05a95def7250883ad97c7b9/test/integration/adapters.js#L52-L58), to make a function that checks that the errors are conform with the QUnit errors and then override them.

- [x] [9] Create a function that builds the global suite for the runStart and runEnd events.

### PR DESCRIPTION
**Pull request by flore77**
Fixes #57.

### CODE REVIEW

File: lib/adapters/QUnitAdapter.js [hunk 1]
```diff
@@ -58,27 +88,23 @@ export default class QUnitAdapter extends EventEmitter {
...
-    } else if (details.skipped === true) {
-      test.status = 'skipped'
-    } else {
-      test.status = 'passed'
-    }
+    var test
 
-    test.runtime = details.runtime
-    test.errors = this.errors
+    details.errors = this.errors
```
Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: I have done this to equal the MochaAdapter, here we can check in the convertTest function for `this.errors`

**Comment by flore77** [comment]
@jzaefferer I know the tests are still failing, but I want to have some feedback for this part.

There are still 2 big issues to solve: `suiteEnd objects` and `nested suites`.

Here is does not function the trick to add to the test object the `errors` property, because QUnit is emitting other objects on each event. So on the `suiteEnd` event, the emitted objects will contain a list of `tests`, but this have only 2 props: `name` and `testId`. We need also `runtime`, `error` and `status`.

I am thinking to index the aforementioned props into an array, something:

```js
var testProps = {}

var props = {
  status: test.status,
  errors: test.errors,
  runtime: test.runtime
}

testProps[test.testId] = props. 
```
So in the `convertTest` function, if we don't have the all the props we need, we can check for them in the `testProps` object.

File: lib/adapters/QUnitAdapter.js [hunk 2]
```diff
@@ -12,22 +12,50 @@ export default class QUnitAdapter extends EventEmitter {
...
+    return new Suite(suiteName, [], tests)
+  }
+
+  /**
+   * @param qunitTest - when passed in from the convertModule function it does
+   *  contain only its "name" and the "testId".
+   * @param suiteNameParam - is used only when calling convertTest from
+   *  the convertModule function, in rest it is undefined.
+   */
+  convertTest (qunitTest, suiteNameParam) {
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: `suiteNameParam` is a weird parameter, since its used only once. I suggest renaming this to `suiteName`, then overwriting this as necessary.

File: lib/adapters/QUnitAdapter.js (hunk 1 above)
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Is this just for consistency, or is it actually needed?

File: lib/adapters/QUnitAdapter.js [hunk 3]
```diff
@@ -12,22 +12,50 @@ export default class QUnitAdapter extends EventEmitter {
...
+    var suiteName = suiteNameParam
+
+    // Assign the name of the module, only if it is not the global one, then
+    // leave the suiteName to be undefined.
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: This is a weird comment, let's try to rephrase this.

File: lib/adapters/QUnitAdapter.js (hunk 1 above)
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: I guess QUnit also doesn't provide aggregated errors, so we need that here.

File: lib/adapters/QUnitAdapter.js [hunk 4]
```diff
@@ -58,27 +88,23 @@ export default class QUnitAdapter extends EventEmitter {
...
-    test.errors = this.errors
+    details.errors = this.errors
+    test = this.convertTest(details)
 
     this.emit('testEnd', test)
   }
 
   onModuleDone (details) {
-    this.emit('suiteEnd', this.idDataMap[details.name])
+    if (details.name !== '') {
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: This isn't a great check, and its now scattered across multiple places in this class. Let's try to at least abstract it, so that we can call `if (this.globalModule(details)) { [...]`.

File: test/fixtures/qunit.js [hunk 5]
```diff
@@ -1,12 +1,16 @@
 var QUnit = require('qunitjs')
 
-QUnit.test('global test', function () {
+// Add dummy assertions in passing tests, because QUnit is checking for at
+// least one assertion, if there is none, then QUnit throws an error and the
+// test fails.
 
+QUnit.test('global test', function () {
+  QUnit.assert.ok(true)
```
Comment (jzaefferer) [inline test/fixtures/qunit.js]: You should define the `assert` argument and use:

```
QUnit.test('global test', function (assert) {
  assert.ok(true)
})
```

**Comment by jzaefferer** [comment]
> So in the convertTest function, if we don't have the all the props we need, we can check for them in the testProps object.

Let's give that a try.

File: lib/adapters/QUnitAdapter.js [hunk 6]
```diff
@@ -58,27 +111,21 @@ export default class QUnitAdapter extends EventEmitter {
...
-    test.errors = this.errors
-
-    this.emit('testEnd', test)
+    details.testEnd = true
+    this.emit('testEnd', this.convertTest(details))
   }
 
   onModuleDone (details) {
-    this.emit('suiteEnd', this.idDataMap[details.name])
+    details.suiteEnd = true
```
Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Notify `convertModule` it must emit a `suite end`.

File: lib/adapters/QUnitAdapter.js [hunk 7]
```diff
@@ -58,27 +111,21 @@ export default class QUnitAdapter extends EventEmitter {
...
-      test.status = 'skipped'
-    } else {
-      test.status = 'passed'
-    }
-
-    test.runtime = details.runtime
-    test.errors = this.errors
-
-    this.emit('testEnd', test)
+    details.testEnd = true
```
Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Notify `convertTest` it must emit a `test end`.

File: lib/adapters/QUnitAdapter.js [hunk 8]
```diff
@@ -13,21 +13,72 @@ export default class QUnitAdapter extends EventEmitter {
...
 
   convertModule (qunitModule) {
     var suiteName = qunitModule.name
     var tests = []
+
     for (let qunitTest of qunitModule.tests) {
-      let test = new Test(qunitTest.name, suiteName)
-      tests.push(test)
-      this.idDataMap[qunitTest.testId] = test
+      qunitTest.testEnd = qunitModule.suiteEnd
```
Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: If a `suite end` must be emitted, notify also `converTest` to emit a `test end`.

**Comment by flore77** [comment]
@jzaefferer please review.

File: lib/adapters/QUnitAdapter.js (hunk 8 above)
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: I don't understand what you're talking about. There are no `emit` calls in `convertTest`

File: lib/adapters/QUnitAdapter.js (hunk 7 above)
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Same as above. Your comment doesn't reflect the implementation. And I don't think we should be adding even more properties to the data we're consuming. We really should consider those objects immutable and track these properties ourselves, like we now do with `this.testsDetails`.

File: lib/adapters/QUnitAdapter.js (hunk 8 above)
Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Yes, sorry, it should to **create** a `test end`.

Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Can you split `convertTest` into 2 methods, one doing the basic conversion, the other doing the `testEnd` work? Then `onTestDone` call both methods.

Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Hmm. Something like:

```js
function saveTestDetails(qunitTest) {
  var testDetails = {}
   // attach the details to the above object
   this.testsDetails[qunitTest.testId] = testDetails
}

function convertTest(qunitTest, suiteName) {
  var testDetails = this.testsDetails[qunitTest.testId]
  
  if (testDetails !== undefined) {
     // emit a test end
  }

  // emit a test start
}

function onTestDone(details) {
  saveTestDetails(qunitTest);
  this.emit('testEnd', convertTest(qunitTest));
}
```

Is this ok ?

Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Yeah, that looks better.

**Comment by flore77** [comment]
Done.

**Comment by jzaefferer** [comment]
That looks better. `npm test` is failing for me with this output:

```
/Users/jzaefferer/dev/jquery/js-reporters/dist/js-reporters.js:1175
          if (actual.name !== expected.name) {
                    ^

TypeError: Cannot read property 'name' of undefined
```
Haven't tried to debug that, yet, are you aware of this issue?

**Comment by flore77** [comment]
Yes, I have seen it, but I still wanted to push, because the integration tests are passing, at least some of them that should pass :laughing: 

> Haven't tried to debug that, yet

I will debug it!
 
Maybe it gets `undefined`, because now there are less events, we do not emit the `globalSuite` twice.

**Comment by flore77** [comment]
I found the problem and it is a bug :disappointed: The `globalModule` is not emitted if it does `not contain` any `tests`, so on the `runEnd` event `this.globalSuiteEnd` will be undefined. In our test fixture we have a global test so everything is functioning well.

**Comment by flore77** [comment]
I would leave this after we found a fix for the nested suites, because also now the suite on the runStart event is not created quite well. After fixing the nesting suites, it would be more clearer how it must be built.

**Comment by jzaefferer** [comment]
I didn't understand your explanations. Let's make `npm test` pass, even if that means skipping a few tests temporarily.

**Comment by flore77** [comment]
The [onBegin](https://github.com/js-reporters/js-reporters/blob/39c02f654ec4ff52de417e5255863885677f7980/lib/adapters/QUnitAdapter.js#L86-L90) function does not emit a suite that respects the standard, because:

- it does not treat nested suites, i.e the `outter suite` has `no childSuites` (it should have the inner suite), `all suites` are putted as `childSuites` of the `globalSuite`
- QUnit global module is wrapped in an another module instead of being the one that wraps all other modules

The [moduleDone](https://github.com/js-reporters/js-reporters/blob/39c02f654ec4ff52de417e5255863885677f7980/lib/adapters/QUnitAdapter.js#L120) functions saves in `this.globalEndSuite` a converted suite that does not contain the other suites, something of this form:

```js
Suite {
  name: '',
  childSuites: [],
  tests: 
   [ Test {
       testName: 'global test',
       suiteName: undefined,
       status: 'passed',
       runtime: 1,
       errors: [] } ] }
```

I was thinking to firstly fix the nested modules, and then to build the `suites` emitted on `runStart` and `runEnd`, because then we will have the big picture, while now we don't now how we will deal with the nested suites.

The `undefined` comes from, because the old test fixture does not have a global test and QUnit does not emit the globalModule anymore on the `suiteStart` and `suiteEnd` events. And so our adapter will never enter on the [else](https://github.com/js-reporters/js-reporters/blob/39c02f654ec4ff52de417e5255863885677f7980/lib/adapters/QUnitAdapter.js#L119), so `this.globalEndSuite` will stay undefined. 

I hope I have explained more clearly :smiley:  

How should I proceed ? Should I know to take care of building the `suites` properly for the `runStart` and `runEnd` events ? Or should I deal with the nested modules ?

**Comment by jzaefferer** [comment]
> The undefined comes from, because the old test fixture does not have a global test and QUnit does not emit the globalModule anymore on the suiteStart and suiteEnd events. And so our adapter will never enter on the else, so this.globalEndSuite will stay undefined.

Is there a simple fix or workaround for that, so that we can make these tests pass while working on other issues?

> How should I proceed ? Should I know to take care of building the suites properly for the runStart and runEnd events ? Or should I deal with the nested modules ?

Either seems fine to me, I can't tell which one is better to start with. Pick one, if you get stuck, try the other?

**Comment by flore77** [comment]
@jzaefferer I have fixed the global suites emitted on the runStart/runEnd events, I am looking forward for your feedback :smiley: 

The 2 tests that are testing this events are still failing, but because of the `name` of the `inner suite`. 

QUnit emits also for suites a concatenated name, the inner suite has the name: `outter suite > inner suite`and in our reference data it has the name `inner suite`. How should this be ?

The inner tests has also a concatenated name, but we must only remove the `>` character. I am waiting to know how we deal with the suite name, then I will solve them both.

**Comment by jzaefferer** [comment]
I'll have to review the `createGlobalSuite` more thorougly later, at a glance it looks good. Nice job!

> QUnit emits also for suites a concatenated name, the inner suite has the name: outter suite > inner suiteand in our reference data it has the name inner suite. How should this be ?

> The inner tests has also a concatenated name, but we must only remove the > character. I am waiting to know how we deal with the suite name, then I will solve them both.

This feels like something we should bring back to QUnit. For now let's just cut of the last `>` and anything before that. That should be simple enough to adjust later.

**Comment by flore77** [comment]
Now remains only to solve the execution of nested modules.

I have seen that also Jasmine executes the nested suites this way, from the inner most to the outer most suite.

How should we do this in our standard ?

Also from what I have seen, QUnit does not emit the start of the `outter suite` and then the start of the `inner suite`, it executes them indepedently, i.e `inner suite starts`, `inner test executes`, `inner suite ends`,  `outer suite starts`, `outer test executes`, `outer suite ends`, so any option we choose, we will have some code to write for the QUnitAdapter.

**Comment by jzaefferer** [comment]
Are the Jasmine and QUnit behaviours at least consistent? Or do they also have differences?

> so any option we choose, we will have some code to write for the QUnitAdapter.

I have no preference, what do you think?

**Comment by flore77** [comment]
> Are the Jasmine and QUnit behaviours at least consistent? Or do they also have differences?

Yes, there are some small differences, but I didn't investigate too deep for Jasmine.

I think the most natural is to run the tests from the outer most suite to the inner most suite, like Mocha does.  Also the **QUnit reporter displays tests in the same order as Mocha**, no matter in which order the tests are executed and emitted.

So, I think definitely to emit the tests from the outer most to the inner most.

I will try today to achieve this for QUnit, I am thinking to buffer all data in our adapter until QUnits calls the done callback and after that to begin emit data from our adapter. This way we can store and order easily the data in a form we like. Sounds ok ?

**Comment by jzaefferer** [comment]
Yes, that sounds good. Could you also file an issue against QUnit, telling them about the difference with Mocha, and the inconsistency in the UI? Maybe they're interested in addressing that before the 2.0.0 release.

**Comment by jzaefferer** [comment]
Before you work on the suites handling, could we skip those 8 failing tests and land this PR? Then work on the suites handling in a separate PR.

**Comment by flore77** [comment]
>  Could you also file an issue against QUnit, telling them about the ...

Hmm, I don't know, QUnit has  2 options that randomizes tests execution:
* the `reorder` option that on a rerun, runs firstly the failed tests, it is activated by default
* the `seed` option that randomizes tests execution, it is disabled by default

The `reorder` option is activated by default and in it description it says:
> this can speed up testing a lot.
It can also lead to random errors, in case your testsuite has non-atomic tests, where the order is important. You should fix those issues, instead of disabling reordering!`

So, I think it is an important feature of QUnit and I think in their reporter they are doing this reordering, because it would be confusing on multiple runs to display tests in a different order.

Of course the inconsistency is that on a normal running they are running the tests from the inner most to the outer most, but displaying them the other way, but I think the reporter cannot be change, because it must handle the other cases of `reorder` and `seed`.  So the change that can be done, would be change the normal running, but I don't know if it would be a gain. 

What do you think? Should I open an issue there to see what they say about it ?

**Comment by jzaefferer** [comment]
Thanks for the details, I hadn't considered those. So no, let's not do that now.

As for this PR, let's skip the remaining failing tests and merge.

**Comment by flore77** [comment]
Yeah, we have a problem, the `rollup-plugin-babel` is causing this: 

[Cannot find module '__babelHelpers__' from '/home/flore77/js-reporters/node_modules/events'](https://github.com/rollup/rollup-plugin-babel/blob/master/CHANGELOG.md), I don't know yet how to solve this, I have forced to stay for now at the 2.4.0.

**Comment by flore77** [comment]
Maybe we should change the assertion of the runtime range, to check only if runtime is a number, like:

`expect(typeof runtime).to.be.equal('number')`.

**Comment by jzaefferer** [comment]
> Maybe we should change the assertion of the runtime range

Let's see if the updated assertion works out, if not, we could still make that change.
