### PR TITLE
Test end assertions prop

### LINKED ISSUE #31: testEnd property for all assertions
QUnit reports all assertions, passing or failing: http://api.qunitjs.com/QUnit.log/

There's no need for all frameworks to provide that, but it would make sense to have an array of assertions on the testEnd event. QUnit could make use of that, other frameworks could just leave it null/undefined, reporters can then see if its there and skip it if not.

### PR DESCRIPTION
**Pull request by flore77**
Fixes #31.

### CODE REVIEW

**Comment by flore77** [comment]
I think it would be good to finish first #79. So that we'll know what to expect and to add here proper testing.

File: lib/adapters/QUnitAdapter.js [hunk 1]
```diff
@@ -178,12 +179,23 @@ export default class QUnitAdapter extends EventEmitter {
...
     this.errors = []
+    this.assertions = []
   }
 
   onLog (details) {
-    if (!details.result) {
-      this.errors.push(details)
+    var assertion = {
+      success: details.result,
+      actual: details.actual || null,
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: This is wrong. Anything falsy is valid here and should not be replaced with `null`. I'd remove the fallback, to keep whatever the property was.

File: lib/adapters/QUnitAdapter.js [hunk 2]
```diff
@@ -178,12 +179,23 @@ export default class QUnitAdapter extends EventEmitter {
...
+      expected: details.expected || null,
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Same here

File: lib/adapters/QUnitAdapter.js [hunk 3]
```diff
@@ -178,12 +179,23 @@ export default class QUnitAdapter extends EventEmitter {
...
+      message: details.message,
+      stack: details.source || undefined
```
Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: This fallback seems unnecessary

Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: I agree with the ones above, but I think this is necessary, because passed assertion must have the stack undefined, at least this is what we discussed in #79

Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Can you verify that `details.source` in QUnit is undefined for passed assertions? If it isn't, we should remove that requirement.

Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Ok, I will check 😃

Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: Yes, it is undefined. More specifically the object emitted on the `log` callback does not have this prop.

Comment (flore77) [inline lib/adapters/QUnitAdapter.js]: For Jasmine the stack property is an empty string. So, I think `undefined` works just fine.

Comment (jzaefferer) [inline lib/adapters/QUnitAdapter.js]: Alright. I probably was thinking of QUnit providing stacks for tests, even when passed...

File: lib/adapters/MochaAdapter.js [hunk 4]
```diff
@@ -52,10 +52,25 @@ export default class MochaAdapter extends EventEmitter {
     // a "test start".
     if (mochaTest.errors !== undefined) {
       var status = (mochaTest.state === undefined) ? 'skipped' : mochaTest.state
-
-      // Test end.
+      let errors = []
+
+      // Mocha has indeed only one error per test, but by this is avoided the
```
Comment (jzaefferer) [inline lib/adapters/MochaAdapter.js]: There's something wrong with the comment here. "but by this is"? Not sure what you're trying to say.

**Comment by jzaefferer** [comment]
Looks good to me. If we land this as-is, the next step needs to be a spec update. Add the `Error` type next to `Suite` and `Test`.

File: lib/adapters/MochaAdapter.js (hunk 4 above)
Comment (flore77) [inline lib/adapters/MochaAdapter.js]: I wanted to make clear why I used `forEach`, although that Mocha has only one error. I will delete I think.

**Comment by flore77** [comment]
Hmm, `Error` type or better `Assertion` type?

File: lib/adapters/MochaAdapter.js (hunk 4 above)
Comment (jzaefferer) [inline lib/adapters/MochaAdapter.js]: Okay

**Comment by jzaefferer** [comment]
You're right, should be `Assertion`.
